# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Justin Pease
email: justin@justinpease.com
description: >- # this means to ignore newlines until "baseurl:"
  Sometimes I write stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://justinpease.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jpease
github_username:  jpease
linkedin_username: justinapease
  
# Google Analytics
google-analytics: G-HMKCNEPC19

# Disqus
disqus-shortname: 
  
# Name of the Author
author-name: Justin Pease
# URL for the Image of the Author
author-image: /assets/images/selfie.jpeg
# 60 Words About the Author
author-about: Remote team builder 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: justinpease.com

# SASS
sass:
  sass_dir: _sass
  style: compressed
    
# Compress
compress_html:
  clippings: all

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-github-metadata

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
